### ISSUE TITLE
ProstgreSQL authentication error

### ISSUE THREAD

**Issue by ldexterldesign** [angristan/feedbin-docker#5]
TODO update issue title to something more descriptive once resolved

How do I fix this error?

I've explored numerous things (e.g. docker paths, default/root postgres user) but first and foremost looks like a redis/postgres issue..?

cli:
```sh
ldexterldesign@Lewiss-MacBook-Pro feedbin-docker % docker-compose run --rm feedbin-web rake db:setup --trace
Starting feedbin-docker_feedbin-redis_1 ...
Starting feedbin-docker_feedbin-postgres_1      ... done
Starting feedbin-docker_feedbin-minio_1         ... done
Starting feedbin-docker_feedbin-memcached_1     ... done
Starting feedbin-docker_feedbin-elasticsearch_1 ... done
I, [2020-03-24T23:53:01.251603 #1]  INFO -- honeybadger: ** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=4.5.6 framework=rails level=1 pid=1
** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:create
FATAL:  password authentication failed for user "feedbin"
Couldn't create 'feedbin_production' database. Please check your configuration.
E, [2020-03-24T23:53:01.583493 #1] ERROR -- honeybadger: ** [Honeybadger] Unable to send error report: API key is missing. id=dbb2e00f-e075-4543-95e9-67acab2454c5 level=3 pid=1
rake aborted!
PG::ConnectionBad: FATAL:  password authentication failed for user "feedbin"
/usr/local/bundle/gems/pg-1.2.2/lib/pg.rb:58:in `initialize'
/usr/local/bundle/gems/pg-1.2.2/lib/pg.rb:58:in `new'
/usr/local/bundle/gems/pg-1.2.2/lib/pg.rb:58:in `connect'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/connection_handling.rb:236:in `retrieve_connection'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/connection_handling.rb:204:in `connection'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/tasks/database_tasks.rb:126:in `create'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/usr/local/bundle/bundler/gems/rails-04e08ee17fb8/activerecord/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create
```

docker:
```sh
Attaching to feedbin-docker_feedbin-postgres_1, feedbin-docker_feedbin-elasticsearch_1, feedbin-docker_feedbin-minio_1, feedbin-docker_feedbin-redis_1, feedbin-docker_feedbin-memcached_1
feedbin-elasticsearch_1 | [2020-03-24 23:42:53,563][WARN ][bootstrap ] unable to install syscall filter: seccomp unavailable: your kernel is buggy and you should upgrade
feedbin-elasticsearch_1 | [2020-03-24 23:42:53,706][INFO ][node ] [Luke Cage] version[2.4.6], pid[1], build[5376dca/2017-07-18T12:17:44Z]
feedbin-elasticsearch_1 | [2020-03-24 23:42:53,706][INFO ][node ] [Luke Cage] initializing ...
feedbin-elasticsearch_1 | [2020-03-24 23:42:54,486][INFO ][plugins ] [Luke Cage] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
feedbin-elasticsearch_1 | [2020-03-24 23:42:54,597][INFO ][env ] [Luke Cage] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [47.2gb], net total_space [58.4gb], spins? [possibly], types [ext4]
feedbin-elasticsearch_1 | [2020-03-24 23:42:54,597][INFO ][env ] [Luke Cage] heap size [494.9mb], compressed ordinary object pointers [true]
feedbin-elasticsearch_1 | [2020-03-24 23:42:57,137][INFO ][node ] [Luke Cage] initialized
feedbin-elasticsearch_1 | [2020-03-24 23:42:57,137][INFO ][node ] [Luke Cage] starting ...
feedbin-elasticsearch_1 | [2020-03-24 23:42:57,321][INFO ][transport ] [Luke Cage] publish_address {172.18.0.6:9300}, bound_addresses {0.0.0.0:9300}
feedbin-elasticsearch_1 | [2020-03-24 23:42:57,328][INFO ][discovery ] [Luke Cage] elasticsearch/W-KZGVi7TFaQPk6nuZRj9w
feedbin-elasticsearch_1 | [2020-03-24 23:43:00,435][INFO ][cluster.service ] [Luke Cage] new_master {Luke Cage}{W-KZGVi7TFaQPk6nuZRj9w}{172.18.0.6}{172.18.0.6:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
feedbin-elasticsearch_1 | [2020-03-24 23:43:00,474][INFO ][http ] [Luke Cage] publish_address {172.18.0.6:9200}, bound_addresses {0.0.0.0:9200}
feedbin-elasticsearch_1 | [2020-03-24 23:43:00,474][INFO ][node ] [Luke Cage] started
feedbin-elasticsearch_1 | [2020-03-24 23:43:00,518][INFO ][gateway ] [Luke Cage] recovered [0] indices into cluster_state
feedbin-postgres_1 |
feedbin-postgres_1 | PostgreSQL Database directory appears to contain a database; Skipping initialization
feedbin-postgres_1 | 2020-03-24 23:42:52.746 UTC [1] LOG: listening on IPv4 address "0.0.0.0", port 5432
feedbin-postgres_1 | 2020-03-24 23:42:52.746 UTC [1] LOG: listening on IPv6 address "::", port 5432
feedbin-postgres_1 | 2020-03-24 23:42:52.749 UTC [1] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
feedbin-postgres_1 | 2020-03-24 23:42:52.767 UTC [27] LOG: database system was shut down at 2020-03-23 00:02:59 UTC
feedbin-minio_1 | ERROR Unable to initialize server switching into safe-mode: Unable to initialize config system: Invalid credentials
feedbin-postgres_1 | 2020-03-24 23:42:52.785 UTC [1] LOG: database system is ready to accept connections
feedbin-postgres_1 | 2020-03-24 23:43:00.188 UTC [34] FATAL: password authentication failed for user "feedbin"
feedbin-postgres_1 | 2020-03-24 23:43:00.188 UTC [34] DETAIL: Password does not match for user "feedbin".
feedbin-postgres_1 | Connection matched pg_hba.conf line 95: "host all all all md5"
feedbin-postgres_1 | 2020-03-24 23:53:01.581 UTC [45] FATAL: password authentication failed for user "feedbin"
feedbin-postgres_1 | 2020-03-24 23:53:01.581 UTC [45] DETAIL: Password does not match for user "feedbin".
feedbin-redis_1 | 1:C 24 Mar 2020 23:42:52.408 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
feedbin-redis_1 | 1:C 24 Mar 2020 23:42:52.408 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
feedbin-redis_1 | 1:C 24 Mar 2020 23:42:52.408 # Configuration loaded
feedbin-redis_1 | 1:M 24 Mar 2020 23:42:52.411 * Running mode=standalone, port=6379.
feedbin-redis_1 | 1:M 24 Mar 2020 23:42:52.412 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
feedbin-redis_1 | 1:M 24 Mar 2020 23:42:52.412 # Server initialized
feedbin-redis_1 | 1:M 24 Mar 2020 23:42:52.412 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
feedbin-redis_1 | 1:M 24 Mar 2020 23:42:52.650 * DB loaded from append only file: 0.238 seconds
feedbin-redis_1 | 1:M 24 Mar 2020 23:42:52.650 * Ready to accept connections
```

cli:
```sh
ldexterldesign@Lewiss-MacBook-Pro feedbin-docker % docker-compose up -d

feedbin-docker_feedbin-minio_1 is up-to-date
feedbin-docker_feedbin-elasticsearch_1 is up-to-date
feedbin-docker_feedbin-redis_1 is up-to-date
feedbin-docker_feedbin-postgres_1 is up-to-date
feedbin-docker_feedbin-memcached_1 is up-to-date
Creating feedbin-docker_camo_1              ... done
Creating feedbin-docker_feedbin-image_1     ... done
Creating feedbin-docker_feedbin-refresher_1 ... done
Creating feedbin-docker_feedbin-workers_1   ... done
Creating feedbin-docker_feedbin-web_1       ... done
Creating feedbin-docker_feedbin-caddy_1     ... done
```

docker:
```sh
[...]
feedbin-workers_1 | 00:08:43 worker_slow.1 | 2020-03-25T00:08:43.965Z pid=10 tid=gr480pj46 WARN: PG::ConnectionBad: FATAL: password authentication failed for user "feedbin"
feedbin-workers_1 | 00:08:43 worker_slow.1 | 2020-03-25T00:08:43.965Z pid=10 tid=gr480pj46 WARN: /usr/local/bundle/gems/pg-1.2.2/lib/pg.rb:58:in `initialize'
```

```sh
ldexterldesign@Lewiss-MacBook-Pro feedbin-docker % docker-compose ps
                 Name                               Command                   State                      Ports
-----------------------------------------------------------------------------------------------------------------------------
feedbin-docker_camo_1                    npm start                        Up (healthy)     127.0.0.1:8081->8081/tcp
feedbin-docker_feedbin-caddy_1           /bin/parent caddy --conf / ...   Restarting
feedbin-docker_feedbin-elasticsearch_1   /docker-entrypoint.sh elas ...   Up (healthy)     127.0.0.1:9200->9200/tcp, 9300/tcp
feedbin-docker_feedbin-image_1           bundle exec foreman start        Up
feedbin-docker_feedbin-memcached_1       docker-entrypoint.sh memcached   Up               11211/tcp
feedbin-docker_feedbin-minio_1           /usr/bin/docker-entrypoint ...   Restarting
feedbin-docker_feedbin-postgres_1        docker-entrypoint.sh postgres    Up               5432/tcp
feedbin-docker_feedbin-redis_1           docker-entrypoint.sh redis ...   Up               6379/tcp
feedbin-docker_feedbin-refresher_1       bundle exec foreman start        Up
feedbin-docker_feedbin-web_1             bundle exec rails s --port ...   Up (unhealthy)   127.0.0.1:3000->3000/tcp
feedbin-docker_feedbin-workers_1         foreman start                    Up               3000/tcp
```

Hope to hear back

Sincerely

.env:

```
# Minio
MINIO_ACCESS_KEY=password
MINIO_SECRET_KEY=password

# Caddy
CADDYPATH=/etc/ssl/caddy

# Camo
CAMO_HOST=https://camo.feedbin.domain.tld
CAMO_KEY=password

# Rails
RACK_ENV=production
RAILS_ENV=production
PORT=3000
SECRET_KEY_BASE=password
DEFAULT_URL_OPTIONS_HOST=feedbin.domain.tld
PUSH_URL=https://feedbin.domain.tld
FEEDBIN_URL=https://feedbin.domain.tld
FEEDBIN_HOST=feedbin.domain.tld
FORCE_SSL=false

# Databases
ELASTICSEARCH_URL=http://elasticsearch:9200
MEMCACHED_HOSTS=memcached:11211
REDIS_URL=redis://feedbin-redis:6379

POSTGRES=postgres
POSTGRES_USERNAME=feedbin
POSTGRES_USER=feedbin
POSTGRES_PASSWORD=password
DATABASE_URL=postgres://feedbin:feedbin@postgres/feedbin_production

# S3
AWS_ACCESS_KEY_ID=password
AWS_SECRET_ACCESS_KEY=password
AWS_S3_BUCKET=feedbin
AWS_S3_BUCKET_FAVICONS=feedbin
AWS_S3_ENDPOINT=https://minio.feedbin.domain.tld
AWS_S3_PATH_STYLE="true"
ENTRY_IMAGE_HOST=minio.feedbin.domain.tld
```

docker-compose.yml:

```
version: '2.2'

volumes:
  feedbin_redis:
  feedbin_db:
  feedbin_elasticsearch:
  feedbin_minio:
  feedbin_caddy:

services:

  feedbin-caddy:
    image: abiosoft/caddy:1.0.3
    volumes:
      - feedbin_caddy:/etc/ssl/caddy
      - ./caddy/Caddyfile:/etc/Caddyfile:ro
    env_file:
     - ./.env
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    links:
      - feedbin-web:feedbin-web
      - feedbin-minio:minio
    restart: always

  feedbin-minio:
    image: minio/minio
    volumes:
    - feedbin_minio:/data
    env_file:
     - ./.env
    command: server /data
    ports:
      - 127.0.0.1:9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    restart: always

  feedbin-web:
    build: .
    ports:
      - 127.0.0.1:3000:3000
    environment:
      PORT: 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    env_file:
     - ./.env
    command: bundle exec rails s --port 3000 --binding 0.0.0.0
    links:
      - feedbin-redis:redis
      - feedbin-postgres:postgres
      - feedbin-elasticsearch:elasticsearch
      - feedbin-memcached:memcached
      - feedbin-minio:minio
    restart: always
    mem_limit: 512m

  feedbin-workers:
    build: .
    env_file:
     - ./.env
    command: foreman start
    links:
      - feedbin-redis:redis
      - feedbin-postgres:postgres
      - feedbin-elasticsearch:elasticsearch
      - feedbin-memcached:memcached
      - feedbin-minio:minio
    restart: always
    mem_limit: 512m

  feedbin-elasticsearch:
    image: elasticsearch:2.4
    ports:
      - 127.0.0.1:9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
    volumes:
      - feedbin_elasticsearch:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    restart: always

  feedbin-refresher:
    build: ./feedbin-refresher
    env_file:
     - ./.env
    links:
      - feedbin-redis:feedbin-redis
    restart: always
    mem_limit: 512m

  feedbin-image:
    build: ./feedbin-image
    env_file:
      - ./.env
    links:
        - feedbin-redis:redis
    restart: always
    mem_limit: 512m

  camo:
    image: inventid/camo
    environment:
      - PORT=8081
    env_file:
     - ./.env
    ports:
      - 127.0.0.1:8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
    restart: always

  feedbin-memcached:
    image: memcached:1.5
    restart: always

  feedbin-redis:
    image: redis:5
    command: "redis-server --appendonly yes"
    volumes:
      - feedbin_redis:/data
    restart: always

  feedbin-postgres:
    image: postgres:10
    env_file:
     - ./.env
    volumes:
      - feedbin_db:/var/lib/postgresql/data
    restart: always
    mem_limit: 512m
```

Caddyfile:

```
feedbin.domain.tld {
  gzip
  proxy / http://feedbin-web:3000 {
    transparent
  }
}

camo.feedbin.domain.tld {
  gzip
  proxy / http://camo:8081 {
    transparent
  }
}

minio.feedbin.domain.tld {
  gzip
  proxy / http://minio:9000 {
    transparent
  }
}
```
