### ISSUE TITLE
letsencrypt.com #Help

### ISSUE THREAD

**Issue by ldexterldesign** [angristan/feedbin-docker#9]
Hi,

Hope you're well

Thanks for ongoing software

After inconsistent success running feedbin locally (i.e. 127.0.0.1:3000) (I think there's a case for making localhost the default setup, un-involving letsencrypt) today I decided to attempt the HTTPS route again and still keep hitting letsencrypt rate limits, and I don't really know why?

Here's my `Caddyfile`:

```
feedbin.ldexterldesign.uk {
  gzip
  proxy / http://feedbin-web:3000 {
    transparent
  }
}

camo.feedbin.ldexterldesign.uk {
  gzip
  proxy / http://camo:8081 {
    transparent
  }
}

minio.feedbin.ldexterldesign.uk {
  gzip
  proxy / http://minio:9000 {
    transparent
  }
}
```

My domain (i.e. ldexterldesign.uk) runs letsencrypt so I don't understand why this won't just work

TODO post specific errors

I suspect I'm hitting rate limits every time I attempt a new install because it's not obvious I have to setup volumes:

Before:

```
[...]
  feedbin-caddy:
    image: abiosoft/caddy:1.0.3
    volumes:
      - feedbin_caddy:/etc/ssl/caddy
      - ./caddy/Caddyfile:/etc/Caddyfile:ro
[...]
```

After:

```
[...]
  feedbin-caddy:
    image: abiosoft/caddy:1.0.3
    volumes:
      - ~/Downloads/-data:/etc/ssl/caddy
      - ~/Downloads/-data:/etc/Caddyfile:ro
[...]
```

[a]biosoft states in its docker hub page:

> [...]
> Saving Certificates
>
> Save certificates on host machine to prevent regeneration every time container starts. Let's Encrypt has rate limit.
> [...]

I'm a letsencrypt newb but if this sounds valid then this should be clearer

Lastly, what does "update the domains" mean in the [R]EADME:

> [...]
> Copy caddy/example.Caddyfile to caddy/Caddyfile and update the domains.
> [...]

Are there any added steps to get an SSL certificate setup (e.g. install and/or run certbot, create a certificate signing request (CSR) and transfer to feedbin?:

* if yes then where in the [t]ree do I dump the CSR
* if no then any help on where I'm going wrong

If you have any issues (e.g. questions/queries) then happy to help

Hope to hear back

Sincerely

a: https://hub.docker.com/r/abiosoft/caddy
l: https://letsencrypt.org/docs/rate-limits/
r: https://github.com/angristan/feedbin-docker#setup

t:
```sh
/Users/ldexterldesign/Downloads/-data/-config/feedbin/caddy
├── acme
│   └── acme-v02.api.letsencrypt.org
│       ├── challenge_tokens
│       └── users
│           └── default
│               ├── default.json
│               └── default.key
├── locks
└── uuid

6 directories, 3 files
```
